# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 16:31
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('instructor', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='SkillRepo',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('start', models.DateTimeField(null=True)),
                ('end', models.DateTimeField(null=True)),
                ('grouped', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('evaluated', models.BooleanField(default=False)),
                ('cowner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='TMS.Course')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='TMS.Task')),
                ('skills', models.ManyToManyField(related_name='_task_skills_+', to='TMS.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='TMSGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cumulative_rep', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TMSUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reputation', models.PositiveIntegerField(default=0)),
                ('colocate_pref', models.BooleanField(default=False)),
                ('skills', models.ManyToManyField(related_name='_tmsuser_skills_+', to='TMS.Skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tmsgroup',
            name='members',
            field=models.ManyToManyField(related_name='groups', to='TMS.TMSUser'),
        ),
        migrations.AddField(
            model_name='task',
            name='uowner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='TMS.TMSUser'),
        ),
        migrations.AddField(
            model_name='skill',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='TMS.SkillRepo'),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='courses', to='TMS.TMSUser'),
        ),
    ]
