# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 23:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmsgroup',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='TMS.Course'),
        ),
    ]
