# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-06 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmsuser',
            name='reputation',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
