# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-22 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmsuser',
            name='skills',
            field=models.ManyToManyField(related_name='_tmsuser_skills_+', through='TMS.UserSkill', to='TMS.Skill'),
        ),
    ]
