# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0002_auto_20160421_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmsgroup',
            name='variance',
            field=models.FloatField(default=0.0),
        ),
    ]
