# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0002_auto_20160318_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grouped', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('evaluated', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='task',
            name='evaluated',
        ),
        migrations.RemoveField(
            model_name='task',
            name='grouped',
        ),
        migrations.AddField(
            model_name='grouptask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='TMS.Task'),
        ),
        migrations.AddField(
            model_name='tmsgroup',
            name='tasks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='TMS.GroupTask'),
        ),
    ]
