# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 21:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0003_auto_20160321_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tmsgroup',
            old_name='tasks',
            new_name='task',
        ),
    ]
