# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0003_tmsgroup_variance'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
