# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0003_task_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='tasks',
        ),
        migrations.RemoveField(
            model_name='tmsuser',
            name='tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='TMS.TMSUser'),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching', to='TMS.TMSUser'),
        ),
    ]
