# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0004_task_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmsuser',
            name='numberofratings',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
