# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0005_auto_20160321_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='cowner',
        ),
        migrations.RemoveField(
            model_name='task',
            name='uowner',
        ),
        migrations.AddField(
            model_name='course',
            name='tasks',
            field=models.ManyToManyField(related_name='_course_tasks_+', to='TMS.Task'),
        ),
        migrations.AddField(
            model_name='tmsuser',
            name='tasks',
            field=models.ManyToManyField(related_name='_tmsuser_tasks_+', to='TMS.Task'),
        ),
    ]
