# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0006_auto_20160307_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='owner',
            new_name='uowner',
        ),
        migrations.AddField(
            model_name='task',
            name='cowner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='TMS.Course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.CharField(max_length=20),
        ),
    ]
