# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 23:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0006_auto_20160321_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='tasks',
        ),
        migrations.RemoveField(
            model_name='tmsuser',
            name='tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='course_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='TMS.TMSUser'),
        ),
        migrations.AddField(
            model_name='task',
            name='user_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='TMS.Course'),
        ),
    ]
