# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0007_auto_20160307_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='evaluated',
            field=models.BooleanField(default=False),
        ),
    ]
